export const service = [
  {
    id: 1,
    image: '/images/service/ambulence.jpg',
    title: '1. Quick ambulence',
    info: 'We have 24/7 type instant ambulance arrangement opportunity for you.',
  },
  {
    id: 2,
    image: '/images/service/blood-bank.jpg',
    title: '2. Sufficient blood bank',
    info: 'Our commitment is to ensure enough blood supply as soon as you need ',
  },
  {
    id: 3,
    image: '/images/service/doctor-service.jpg',
    title: '3. Experience Doctors',
    info: 'Our unbelievable service is to arranment an experienced doctors team for your behalf',
  },
  {
    id: 4,
    image: '/images/service/medicine.jpg',
    title: '4. Intake Medicine',
    info: 'We lead actual and valid medicine service and give lovely effort to arrange your required medicine',
  },
  {
    id: 5,
    image: '/images/service/operation-theater.jpg',
    title: '5. Rich Operation theater',
    info: 'Everyday operable theather with all the modern tools',
  },
  {
    id: 6,
    image: '/images/service/Dental.jpg',
    title: '5. Expert Dental Guide',
    info: 'Now famouse and expert detanl graduates are avaiable with us',
  },
]

export const online = [
  {
    id: 1,
    title: 'Allergy',
    image: '/images/online/allergy.png',
    action: 'Click to consult',
  },
  {
    id: 2,
    title: 'Psychiatry',
    image: '/images/online/psychiatry.png',
    action: 'Click to consult',
  },
  {
    id: 3,
    title: 'Dermatology',
    image: '/images/online/dermatology.png',
    action: 'Click to consult',
  },
  {
    id: 4,
    title: 'Family medicine',
    image: '/images/online/family_madicine.png',
    action: 'Click to consult',
  },
  {
    id: 5,
    title: 'Obstetrics & gynecology',
    image: '/images/online/obstetrics.png',
    action: 'Click to consult',
  },
  {
    id: 6,
    title: 'Ophthalmology',
    image: '/images/online/Ophthalmology.png',
    action: 'Click to consult',
  },
  {
    id: 7,
    title: 'Pediatrics',
    image: '/images/online/Pediatrics.png',
    action: 'Click to consult',
  },
  {
    id: 8,
    title: 'Urology',
    image: '/images/online/Urology.png',
    action: 'Click to consult',
  },
]

export const clinic = [
  {
    id: 1,
    title: 'Cardiology',
    image: '/images/clinic/Cardic.jpg',
    info: 'Cardiology is a branch of medicine that deals with disorders of the heart and the cardiovascular system. The field includes medical diagnosis and treatment of congenital heart defects',
  },
  {
    id: 2,
    title: 'Cold, Cough & Fever',
    image: '/images/clinic/Cold, Cough & Fever.png',
    info: 'Cold symptoms usually begin with a sore throat, which usually goes away after a day or two. Nasal symptoms, runny nose, and congestion follow, along with a cough by the fourth and fifth days',
  },
  {
    id: 3,
    title: 'Colorectal Surgery',
    image: '/images/clinic/Colorectal Surgery.jpg',
    info: 'Colorectal surgery is a field in medicine dealing with disorders of the rectum, anus, and colon. ... The field is also known as proctology, but this term is now',
  },
  {
    id: 4,
    title: 'Dentist',
    image: '/images/clinic/Dentist.jpg',
    info: 'Dentistry, also known as dental medicine and oral medicine, is the branch of medicine focused on the teeth, gums, and mouth',
  },
  {
    id: 5,
    title: 'Diabetology',
    image: '/images/clinic/Diabetology.jpg',
    info: 'Diabetology. Diabetology is an international, peer-reviewed, open access journal on diabetes research published quarterly online by MDPI. Open Access— free for ',
  },
  {
    id: 6,
    title: 'ENT',
    image: '/images/clinic/ENT.jpg',
    info: 'Otorhinolaryngology is a surgical subspeciality within medicine that deals with the surgical and medical management of conditions of the head and neck',
  },
  {
    id: 7,
    title: 'Hematology',
    image: '/images/clinic/Hematology.jpeg',
    info: 'Hematology is the study of blood and blood disorders. Hematologists and hematopathologists are highly trained healthcare providers who specialize in diseases of the blood and blood components.',
  },
]

export const slider = [
  {
    id: 1,
    name: 'Expert Team',
    image: '/images/Slide-1.jpg',
    description: 'We are aware of making team with experts!',
  },
  {
    id: 2,
    name: 'Service is quick',
    image: '/images/Slide-2.png',
    description: 'We believe quick service can save life!',
  },
  {
    id: 3,
    name: 'Intensive care',
    image: '/images/Slide-3.jpg',
    description: 'Intensive care is our primary goal and make patients happy',
  },
  {
    id: 4,
    name: 'Speciality matters',
    image: '/images/Slide-4.jpg',
    description: 'We are not used to compromise with lack of speciality',
  },
  {
    id: 5,
    name: 'Donation and help',
    image: '/images/Slide-6.jpg',
    description: 'Our donation should go for intensive necessity',
  },
]

export const hospitals = [
  {
    id: 1,
    hospital: 'Apollo',
    images: '/hospital/Apollo.jpg',
    name: 'Name1',
    doctor: '/hospital/doctors/doctor1.png',
    specialisation: 'Pulmonologist',
    experience: '3 years',
  },
  {
    id: 2,
    hospital: 'Apollo',
    images: '/hospital/Apollo.jpg',
    name: 'Name2',
    doctor: '/hospital/doctors/doctor2.jpg',
    specialisation: 'Neurology',
    experience: '2 years',
  },
  {
    id: 3,
    hospital: 'Apollo',
    images: '/hospital/Apollo.jpg',
    name: 'Name3',
    doctor: '/hospital/doctors/doctor1.png',
    specialisation: 'Pulmonologist',
    experience: '5 years',
  },
  {
    id: 4,
    hospital: 'Apollo',
    images: '/hospital/Apollo.jpg',
    name: 'Name4',
    doctor: '/hospital/doctors/doctor3.png',
    specialisation: 'Batiatrics',
    experience: '4 years',
  },

  {
    id: 5,
    hospital: 'Fortis',
    images: '/hospital/fortis.jpg',
    doctor: '/hospital/doctors/doctor2.jpg',
    name: 'Name1',
    specialisation: 'Batiatrics',
    experience: '4 years',
  },
  {
    id: 6,
    hospital: 'Fortis',
    images: '/hospital/fortis.jpg',
    name: 'Name2',
    doctor: '/hospital/doctors/doctor5.png',
    specialisation: 'Pulmonologist',
    experience: '3 years',
  },
  {
    id: 7,
    hospital: 'Fortis',
    images: '/hospital/fortis.jpg',
    name: 'Name3',
    doctor: '/hospital/doctors/doctor4.png',
    specialisation: 'Batiatrics',
    experience: '5 years',
  },
  {
    id: 8,
    hospital: 'Fortis',
    images: '/hospital/fortis.jpg',
    name: 'Name4',
    doctor: '/hospital/doctors/doctor1.png',
    specialisation: 'Cardiology',
    experience: '2 years',
  },
  {
    id: 9,
    hospital: 'Savron',
    images: '/hospital/savron.jpg',
    name: 'Name1',
    doctor: '/hospital/doctors/doctor6.png',
    specialisation: 'Pulmonologist',
    experience: '8 years',
  },
  {
    id: 10,
    hospital: 'Savron',
    images: '/hospital/savron.jpg',
    name: 'Name2',
    doctor: '/hospital/doctors/doctor5.png',
    specialisation: 'Neurology',
    experience: '6 years',
  },
  {
    id: 11,
    hospital: 'Savron',
    images: '/hospital/savron.jpg',
    name: 'Name3',
    doctor: '/hospital/doctors/doctor3.png',
    specialisation: 'Neurology',
    experience: '4 years',
  },
  {
    id: 12,
    hospital: 'Savron',
    images: '/hospital/savron.jpg',
    name: 'Name4',
    doctor: '/hospital/doctors/doctor1.png',
    specialisation: 'Batiatrics',
    experience: '7 years',
  },
  {
    id: 13,
    hospital: 'Memon hospital',
    images: '/hospital/memon.jpg',
    name: 'Name1',
    doctor: '/hospital/doctors/doctor1.png',
    specialisation: 'Pulmonologist',
    experience: '1 years',
  },
  {
    id: 14,
    hospital: 'Memon hospital',
    images: '/hospital/memon.jpg',
    name: 'Name2',
    doctor: '/hospital/doctors/doctor4.png',
    specialisation: 'Cardiology',
    experience: '4 years',
  },
  {
    id: 15,
    hospital: 'Memon hospital',
    images: '/hospital/memon.jpg',
    name: 'Name3',
    doctor: '/hospital/doctors/doctor2.jpg',
    specialisation: 'Paediatrics',
    experience: '3 years',
  },
  {
    id: 16,
    hospital: 'Memon hospital',
    images: '/hospital/memon.jpg',
    name: 'Name4',
    doctor: '/hospital/doctors/doctor5.png',
    specialisation: 'Cardiology',
    experience: '9 years',
  },
  {
    id: 17,
    hospital: 'National hospital',
    images: '/hospital/national.jpg',
    name: 'Name1',
    doctor: '/hospital/doctors/doctor1.png',
    specialisation: 'Cardiology',
    experience: '6 years',
  },
  {
    id: 18,
    hospital: 'National hospital',
    images: '/hospital/national.jpg',
    name: 'Name2',
    doctor: '/hospital/doctors/doctor4.png',
    specialisation: 'Paediatrics',
    experience: '4 years',
  },
  {
    id: 19,
    hospital: 'National hospital',
    images: '/hospital/national.jpg',
    name: 'Name3',
    doctor: '/hospital/doctors/doctor6.png',
    specialisation: 'Cardiology',
    experience: '3 years',
  },
  {
    id: 20,
    hospital: 'National hospital',
    images: '/hospital/national.jpg',
    name: 'Name4',
    doctor: '/hospital/doctors/doctor5.png',
    specialisation: 'Paediatrics',
    experience: '4 years',
  },
  {
    id: 21,
    hospital: 'Modern hospital',
    images: '/hospital/modern.jpg',
    name: 'Name1',
    doctor: '/hospital/doctors/doctor6.png',
    specialisation: 'Neurology',
    experience: '4 years',
  },
  {
    id: 22,
    hospital: 'Modern hospital',
    images: '/hospital/modern.jpg',
    name: 'Name2',
    doctor: '/hospital/doctors/doctor1.png',
    specialisation: 'Paediatrics',
    experience: '7 years',
  },
  {
    id: 23,
    hospital: 'Modern hospital',
    images: '/hospital/modern.jpg',
    name: 'Name3',
    doctor: '/hospital/doctors/doctor2.jpg',
    specialisation: 'Radiology',
    experience: '4 years',
  },
  {
    id: 24,
    hospital: 'Modern hospital',
    images: '/hospital/modern.jpg',
    name: 'Name4',
    doctor: '/hospital/doctors/doctor5.png',
    specialisation: 'Paediatrics',
    experience: '1 years',
  },
]

export const ambulances = [
  {
    id: 1,
    images: ['/ambulance/a-c-ambulance.png', '/ambulance/Ac-ambulance.jpg'],
    details:
      'AC ambulances are also called Basic Life Support Ambulance, which are primarily used for transporting patients who are medically stable and do not require constant monitoring.',
    type: 'AC Ambulance',
    info: [
      'Get ambulance with 30 minutes',
      '24/7 affordable quality service',
      'we are just a call away: +880-01******8',
    ],
    owner: 'ABC',
    pickpoint: 'Infront of ABC hospital',
  },
  {
    id: 2,
    images: ['/ambulance/air-ambu.jpg', '/ambulance/air-ambulance.jpeg'],
    details:
      'AIR Ambulances are also called Basic Life Support Ambulance, which are primarily used for transporting patients who are medically stable and do not require constant monitoring.',
    type: 'AIR Ambulance',
    info: [
      'Get ambulance with 30 minutes',
      '24/7 affordable quality service',
      'we are just a call away: +880-01******8',
    ],
    owner: 'ABC',
    pickpoint: 'Infront of ABC hospital',
  },
  {
    id: 3,
    images: ['/ambulance/als.jpg', '/ambulance/als-ambulance.jpg'],
    details:
      'ALS Ambulances are also called Basic Life Support Ambulance, which are primarily used for transporting patients who are medically stable and do not require constant monitoring.',
    type: 'ALS Ambulance',
    info: [
      'Get ambulance with 30 minutes',
      '24/7 affordable quality service',
      'we are just a call away: +880-01******8',
    ],
    owner: 'ABC',
    pickpoint: 'Infront of ABC hospital',
  },
  {
    id: 4,
    images: ['/ambulance/freezing_car.jpg', '/ambulance/Freezing-Car.jpg'],
    details:
      'Freezing Ambulances are also called Basic Life Support Ambulance, which are primarily used for transporting patients who are medically stable and do not require constant monitoring.',
    type: 'Freezing Ambulance',
    info: [
      'Get ambulance with 30 minutes',
      '24/7 affordable quality service',
      'we are just a call away: +880-01******8',
    ],
    owner: 'ABC',
    pickpoint: 'Infront of ABC hospital',
  },
  {
    id: 5,
    images: ['/ambulance/icu-ambulance.jpg', '/ambulance/icu.jpg'],
    details:
      'ICU Ambulances are also called Basic Life Support Ambulance, which are primarily used for transporting patients who are medically stable and do not require constant monitoring.',
    type: 'ICU Ambulance',
    info: [
      'Get ambulance with 30 minutes',
      '24/7 affordable quality service',
      'we are just a call away: +880-01******8',
    ],
    owner: 'ABC',
    pickpoint: 'Infront of ABC hospital',
  },
]

export const specialities = [
  {
    id: 1,
    image: '/specialities/cancer.png',
    name: 'Cancer',
  },
  {
    id: 2,
    image: '/specialities/cardiology.png',
    name: 'Cardiology',
  },
  {
    id: 3,
    image: '/specialities/plastic-surgery.png',
    name: 'General Surgery',
  },
  {
    id: 4,
    image: '/specialities/abortion.png',
    name: 'Gynecology',
  },
  {
    id: 5,
    image: '/specialities/stomach.png',
    name: 'Gastroenterology',
  },
  {
    id: 6,
    image: '/specialities/bariatric-surgery.png',
    name: 'Bariatric Surgery',
  },

  {
    id: 7,
    image: '/specialities/liver.png',
    name: 'Liver',
  },
  {
    id: 8,
    image: '/specialities/brain.png',
    name: 'Neuro',
  },
  {
    id: 9,
    image: '/specialities/spine.png',
    name: 'Spine',
  },
  {
    id: 10,
    image: '/specialities/kidney.png',
    name: 'Nephrology',
  },
  {
    id: 11,
    image: '/specialities/urology.png',
    name: 'Urology',
  },
  {
    id: 12,
    image: '/specialities/orthopedics.png',
    name: 'Orthopedics',
  },
  {
    id: 13,
    image: '/specialities/one.png',
    name: 'Rheumatology',
  },
  {
    id: 14,
    image: '/specialities/pediatrics.png',
    name: 'Pediatric',
  },
  {
    id: 15,
    image: '/specialities/massage.png',
    name: 'Physiotherapy',
  },
  {
    id: 16,
    image: '/specialities/transplantation.png',
    name: 'Transplantation',
  },
  {
    id: 17,
    image: '/specialities/Laparoscopic.png',
    name: 'Laparoscopic Surgery',
  },
]
 

